# Generated by Django 4.1.4 on 2022-12-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_lecturer_email_alter_lecturer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
