# Generated by Django 4.1.4 on 2023-01-15 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquiz',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='finalquizquestion',
            name='related_quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.finalquiz', verbose_name='Quiz id'),
        ),
        migrations.AddField(
            model_name='finalquizanswer',
            name='related_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.finalquizquestion'),
        ),
        migrations.AddField(
            model_name='finalquiz',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course id'),
        ),
        migrations.AddField(
            model_name='finalquiz',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='finalquiz',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
