# Generated by Django 4.1.4 on 2022-12-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswermodel',
            name='files',
            field=models.FileField(blank=True, upload_to='uploads/homework/8ebebf82-1ddb-4f2f-a70b-28764b79ed59'),
        ),
    ]
