# Generated by Django 4.1.4 on 2022-12-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homeworkanswermodel_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswermodel',
            name='files',
            field=models.FileField(blank=True, upload_to='uploads/homework/749b91e5-bff4-4828-95f8-296262a8351d'),
        ),
    ]
