# Generated by Django 4.1.4 on 2023-01-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_squashed_0004_alter_homeworkanswermodel_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswermodel',
            name='files',
            field=models.FileField(blank=True, upload_to='uploads/homework/35b47960-dcbd-4c47-bf81-464458a259b2'),
        ),
    ]
