# Generated by Django 4.1.5 on 2023-02-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_alter_homeworkanswermodel_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswermodel',
            name='files',
            field=models.FileField(blank=True, upload_to='uploads/homework/355b4413-6339-4334-a638-d3dfd2b751fe'),
        ),
    ]
